import {test} from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,stat} from 'node:fs/promises';import {join} from 'node:path';import {connect} from 'node:net';import {once} from 'node:events';import WebSocket from 'ws';
import {createBridge} from '../src/bridge.ts';import {tmpdir} from 'node:os';
async function setup(){const dir=await mkdtemp(join(tmpdir(),'ma-bridge-'));const b=await createBridge({state:dir,config:{token:'private'},deadlineMs:60,authMs:30,healthMs:1000});return{b,dir,close:async()=>{await b.close();await rm(dir,{recursive:true,force:true});}};}
async function req(path:string,obj:any){const s=connect(path);await once(s,'connect');s.end(JSON.stringify(obj)+'\n');let out='';for await(const b of s)out+=b;return JSON.parse(out);}
async function browser(b:any){const w=new WebSocket(b.url,{origin:'null'});await once(w,'open');w.send(JSON.stringify({type:'hello',secret:b.secret}));const [data]=await once(w,'message');assert.equal(JSON.parse(String(data)).type,'config');return w;}
test('owner-only socket and local status; rejects forbidden commands',async()=>{const x=await setup();try{assert.equal((await stat(x.b.socketPath)).mode&0o777,0o600);assert.equal((await req(x.b.socketPath,{command:'local/status',args:{}})).result.ready,false);assert.equal((await req(x.b.socketPath,{command:'auth',args:{}})).error,'RPC_RESERVED');}finally{await x.close();}});
test('reject website origins and unauthenticated browser; first-message auth required',async()=>{const x=await setup();try{const evil=new WebSocket(x.b.url,{origin:'https://evil.test'});await once(evil,'error');const w=new WebSocket(x.b.url,{origin:'null'});await once(w,'open');w.send(JSON.stringify({type:'hello',secret:'bad'}));await once(w,'close');}finally{await x.close();}});
test('same browser session routes RPC, sanitizes status/errors, and times out',async()=>{const x=await setup();try{const w=await browser(x.b);w.send(JSON.stringify({type:'status',status:{phase:'ready',ready:true,token:'private'}}));w.on('message',d=>{const m=JSON.parse(String(d));if(m.command==='players/get')w.send(JSON.stringify({type:'result',id:m.id,result:[1,2]}));if(m.command==='players/bad')w.send(JSON.stringify({type:'result',id:m.id,error:'private'}));});
 assert.deepEqual(await req(x.b.socketPath,{command:'players/get',args:{}}),{result:[1,2]});assert.deepEqual(await req(x.b.socketPath,{command:'players/bad',args:{}}),{error:'INTERNAL'});assert.deepEqual(await req(x.b.socketPath,{command:'players/hang',args:{}}),{error:'BRIDGE_TIMEOUT'});assert.ok(!JSON.stringify(await req(x.b.socketPath,{command:'local/status',args:{}})).includes('private'));w.terminate();}finally{await x.close();}});
